// Generated by CoffeeScript 1.6.2
(function() {
  var attach, handleFailure, handleResult, handleSuccess;

  handleResult = function(commands, currentCommandNumber, result, context, cb) {
    if (result.exitCode === 0) {
      return handleSuccess(commands, currentCommandNumber, context, cb);
    } else {
      return handleFailure(result.stderr, cb);
    }
  };

  handleFailure = function(errStack, cb) {
    return cb(new Error(errStack));
  };

  handleSuccess = function(commands, currentCommandNumber, context, cb) {
    if (currentCommandNumber < commands.length - 1) {
      currentCommandNumber++;
      return context.libs.runner.runCommand(context, commands, currentCommandNumber, cb);
    } else {
      return cb(null);
    }
  };

  attach = function(libs) {
    return libs.handler = handleResult;
  };

  module.exports = attach;

}).call(this);
