// Generated by CoffeeScript 1.6.2
(function() {
  var Redstone, libs, sshclient;

  sshclient = require('node-sshclient');

  libs = {};

  require('./logger')(libs);

  require('./loader')(libs);

  require('./runner')(libs);

  require('./handler')(libs);

  Redstone = (function() {
    function Redstone(options) {
      var args, name, _ref;

      this.options = options;
      this.ssh = new sshclient.SSH(this.options.ssh);
      this.libs = libs;
      _ref = this.options.commands;
      for (name in _ref) {
        args = _ref[name];
        this.libs.loader(this, name, args);
      }
    }

    Redstone.prototype.runCommands = function(commands, cb) {
      return this.libs.runner.runCommands(this, commands, cb);
    };

    return Redstone;

  })();

  module.exports = Redstone;

}).call(this);
