// Generated by CoffeeScript 1.6.2
(function() {
  var attach, loader;

  loader = function(context, name, args) {
    var _this = this;

    return context[name] = function(cb) {
      return context.ssh.command(args, function(result) {
        context.libs.logger(name, args, result);
        return cb(result);
      });
    };
  };

  attach = function(libs) {
    return libs.loader = loader;
  };

  module.exports = attach;

}).call(this);
