// Generated by CoffeeScript 1.6.2
(function() {
  var attach, logger;

  logger = function(name, args, result) {
    if (result.exitCode === 0) {
      console.log(result.stdout.green);
      return console.log(("✔ " + args).green);
    } else {
      console.log(result.stderr.red);
      return console.log(("✘ " + args).red);
    }
  };

  attach = function(libs) {
    return libs.logger = logger;
  };

  module.exports = attach;

}).call(this);
