// Generated by CoffeeScript 1.6.2
(function() {
  var attach, runCommand, runCommands;

  runCommands = function(context, commands, cb) {
    var currentCommandNumber;

    currentCommandNumber = 0;
    return runCommand(context, commands, currentCommandNumber, function(err) {
      if (typeof cb === 'function') {
        return cb(err);
      }
    });
  };

  runCommand = function(context, commands, currentCommandNumber, cb) {
    var commandToRun;

    commandToRun = commands[currentCommandNumber];
    return context[commandToRun](function(result) {
      return context.libs.handler(commands, currentCommandNumber, result, context, cb);
    });
  };

  attach = function(libs) {
    return libs.runner = {
      runCommands: runCommands,
      runCommand: runCommand
    };
  };

  module.exports = attach;

}).call(this);
